//#pragma config(Motor,  motorB,          leftWheel,     tmotorNXT, PIDControl, driveLeft, encoder)
//#pragma config(Motor,  motorC,          rightWheel,    tmotorNXT, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
#pragma DebuggerWindows("joystickSimple")

float moveSpeed = .3;
float deadZone = 10;

task main()
{
	while(true)
	{
		getJoystickSettings(joystick);
		float y[2] = {joystick.joy1_y1,joystick.joy1_y2};

		if(abs(y[0]) > deadZone)
			motor[motorB] = moveSpeed*y[0]*(100/(128-deadZone));
		else
			motor[motorB] = 0;
		if(abs(y[1]) > deadZone)
			motor[motorC] = moveSpeed*y[1]*(100/(128-deadZone));
		else
			motor[motorC] = 0;

		if(joy1Btn(5)==1)
		{
			moveSpeed = .5;
		}
		if(joy1Btn(7)==1)
		{
			moveSpeed = .3;
		}
		if(joy1Btn(6)==1)
		{
			moveSpeed = .7;
		}
		if(joy1Btn(8)==1)
		{
			moveSpeed = 1;
		}
	}
}
